import * as db from './db.js';
const SESSION_KEY='ae_supabase_session';
function cleanUrl(u){return String(u||'').trim().replace(/\/$/,'')}
async function cfg(){return {url:cleanUrl(await db.getSetting('cloud.url','')),key:String(await db.getSetting('cloud.key','')).trim()}}
export async function configure(url,key){await db.setSetting('cloud.url',cleanUrl(url));await db.setSetting('cloud.key',String(key||'').trim())}
export function session(){try{return JSON.parse(sessionStorage.getItem(SESSION_KEY)||'null')}catch{return null}}
export function logout(){sessionStorage.removeItem(SESSION_KEY)}
async function request(path,{method='GET',body,token,headers={}}={}){
 const c=await cfg(); if(!c.url||!c.key)throw new Error('Configura primeiro o URL e a chave publishable/anon do Supabase.');
 const r=await fetch(c.url+path,{method,headers:{apikey:c.key,Authorization:`Bearer ${token||c.key}`,'Content-Type':'application/json',...headers},body:body===undefined?undefined:JSON.stringify(body)});
 const txt=await r.text();let data=null;try{data=txt?JSON.parse(txt):null}catch{data=txt}
 if(!r.ok)throw new Error(data?.msg||data?.message||data?.error_description||data?.details||`HTTP ${r.status}`);return data;
}
export async function login(email,password){const data=await request('/auth/v1/token?grant_type=password',{method:'POST',body:{email,password}});const s={access_token:data.access_token,refresh_token:data.refresh_token,user:data.user,expires_at:Date.now()+Number(data.expires_in||3600)*1000};sessionStorage.setItem(SESSION_KEY,JSON.stringify(s));return s}
export async function ensureSession(){let s=session();if(!s)throw new Error('Sessão Cloud não iniciada.');if(s.expires_at-Date.now()>60000)return s;const data=await request('/auth/v1/token?grant_type=refresh_token',{method:'POST',body:{refresh_token:s.refresh_token}});s={access_token:data.access_token,refresh_token:data.refresh_token||s.refresh_token,user:data.user||s.user,expires_at:Date.now()+Number(data.expires_in||3600)*1000};sessionStorage.setItem(SESSION_KEY,JSON.stringify(s));return s}
export async function schemaVersion(){const s=await ensureSession();const rows=await request('/rest/v1/ae_schema_migrations?select=version,applied_at&order=applied_at.desc&limit=1',{token:s.access_token});return rows?.[0]?.version||'—'}
export async function testConnection(){const s=await ensureSession();await request('/rest/v1/ae_sync_records?select=id&limit=1',{token:s.access_token});return {email:s.user?.email||'',schema:await schemaVersion()}}
const SYNC_STORES=['settings','clients','suppliers','materials','products','productMaterials','molds','orders','orderItems','payments','purchases','expenses','investments','cashMovements','productionBatches','stockMovements','collections','kitItems','catalogs','homepage','campaigns','deliverySettings','recurringExpenses','transfers','themes','occasions','colors','personalizations','creatorPricing','unavailableDates','notifications','quoteHistory'];
export async function pushAll(){const s=await ensureSession();let n=0;for(const store of SYNC_STORES){const rows=await db.all(store);for(const row of rows){const updated=row.updatedAt||row.updated_at||row.createdAt||new Date().toISOString();const payload={entity:store,record_id:String(row.id),data:{...row,updatedAt:updated},client_updated_at:updated};await request('/rest/v1/ae_sync_records?on_conflict=owner_id,entity,record_id',{method:'POST',token:s.access_token,body:payload,headers:{Prefer:'resolution=merge-duplicates,return=minimal'}});n++}}await db.setSetting('cloud.lastPush',new Date().toISOString());return n}
export async function pullAll(){const s=await ensureSession();const rows=await request('/rest/v1/ae_sync_records?select=entity,record_id,data,client_updated_at,updated_at&deleted_at=is.null',{token:s.access_token});let applied=0,skipped=0;for(const r of rows||[]){if(!SYNC_STORES.includes(r.entity)||!r.data?.id)continue;const local=await db.get(r.entity,r.data.id);const lt=new Date(local?.updatedAt||local?.updated_at||local?.createdAt||0).getTime();const rt=new Date(r.client_updated_at||r.updated_at||0).getTime();if(!local||rt>=lt){await db.put(r.entity,{...r.data,updatedAt:r.client_updated_at||r.updated_at});applied++}else skipped++}await db.setSetting('cloud.lastPull',new Date().toISOString());return {applied,skipped,total:(rows||[]).length}}
export async function status(){const c=await cfg();const s=session();return {configured:!!(c.url&&c.key),loggedIn:!!s,email:s?.user?.email||'',lastPush:await db.getSetting('cloud.lastPush',''),lastPull:await db.getSetting('cloud.lastPull','')}}
