export const qs=s=>document.querySelector(s);
export const esc=s=>String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
export function el(tag,attrs={},...children){const n=document.createElement(tag);for(const[k,v]of Object.entries(attrs)){if(k==='class')n.className=v;else if(k.startsWith('on'))n.addEventListener(k.slice(2).toLowerCase(),v);else if(v!==undefined&&v!==null)n.setAttribute(k,v);}for(const c of children.flat()){if(c===null||c===undefined)continue;n.append(c.nodeType?c:document.createTextNode(String(c)));}return n;}
export function button(text,onClick,kind='secondary'){return el('button',{class:`btn ${kind}`,type:'button',onclick:onClick},text);}
export function badge(text,kind='info'){return `<span class="badge ${kind}">${esc(text)}</span>`}
export function table(headers,rows){const wrap=el('div',{class:'table-wrap'});const t=el('table',{class:'table'});t.innerHTML=`<thead><tr>${headers.map(h=>`<th>${esc(h)}</th>`).join('')}</tr></thead><tbody>${rows.length?rows.map(r=>`<tr>${r.map(c=>`<td>${c??''}</td>`).join('')}</tr>`).join(''):`<tr><td colspan="${headers.length}" class="empty">Sem registos.</td></tr>`}</tbody>`;wrap.append(t);return wrap;}
export function modal(title,body,{saveText='Guardar',onSave,onClose}={}){const root=qs('#modalRoot');const back=el('div',{class:'modal-backdrop'});const box=el('div',{class:'modal'});const close=()=>{root.innerHTML='';onClose?.()};const head=el('div',{class:'modal-head'},el('strong',{},title),button('×',close,'ghost'));const content=el('div',{class:'modal-body'},body);const foot=el('div',{class:'modal-foot'},button('Cancelar',close,'ghost'));if(onSave)foot.append(button(saveText,async()=>{const ok=await onSave();if(ok!==false)close();},'primary'));box.append(head,content,foot);back.append(box);back.addEventListener('click',e=>{if(e.target===back)close()});root.innerHTML='';root.append(back);}
export function field(label,input,span2=false){return el('div',{class:`field${span2?' span2':''}`},el('label',{},label),input)}
export const input=(name,value='',type='text',extra={})=>el('input',{name,value,type,...extra});
export function select(name,options,value=''){const s=el('select',{name});for(const [v,l] of options){const o=el('option',{value:v},l);if(String(v)===String(value))o.selected=true;s.append(o);}return s;}
export const textarea=(name,value='')=>{const t=el('textarea',{name});t.value=value||'';return t};
export function download(name,text,type='application/json'){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([text],{type}));a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
