import * as db from './db.js';
import {families,materialCategories,orderStatuses,euro,uid,calcProduct,nextSku} from './domain.js';
import {el,button,badge,table,modal,field,input,select,textarea,download,esc} from './ui.js';
import {runAudit} from './audit.js';

const fmtDate=v=>v?new Intl.DateTimeFormat('pt-PT').format(new Date(v)):'';
const familyOptions=()=>Object.entries(families).map(([k,v])=>[k,`${v.icon} ${v.label}`]);
const statusKind=s=>/Entregue|Pronta|Pago|Conclu/i.test(s)?'ok':/Cancel/i.test(s)?'danger':/produção/i.test(s)?'violet':/Orçamento/i.test(s)?'warn':'info';

export async function todayView(ctx){
  const [orders,products,materials,production,payments]=await Promise.all(['orders','products','materials','productionBatches','payments'].map(db.all));
  const today=new Date().toISOString().slice(0,10);
  const pending=orders.filter(o=>!['Entregue','Cancelada'].includes(o.status));
  const due=pending.filter(o=>o.dueDate===today);
  const critical=materials.filter(m=>Number(m.stock)<=Number(m.minStock||0));
  const activeProduction=production.filter(p=>p.status!=='Pronto');
  const root=el('div',{class:'grid'});
  root.append(el('div',{class:'quick-grid'},
    quick('🧾','Nova encomenda','Registar pedido do cliente',()=>ctx.go('orders',{create:true})),
    quick('🕯️','Iniciar produção','Abrir trabalho no atelier',()=>ctx.go('atelier',{create:true})),
    quick('📦','Registar compra','Atualizar stock e custo médio',()=>ctx.go('materials',{purchase:true})),
    quick('✨','Novo produto','Criar produto e ficha técnica',()=>ctx.go('catalog',{create:true}))
  ));
  root.append(el('div',{class:'grid cols-4'},kpi('Encomendas abertas',pending.length),kpi('Para hoje',due.length),kpi('Em produção',activeProduction.length),kpi('Stock crítico',critical.length)));
  const left=el('div',{class:'card'},el('div',{class:'section-title'},el('h2',{},'Trabalho em curso'),button('Abrir Atelier',()=>ctx.go('atelier'),'ghost')));
  if(activeProduction.length){for(const p of activeProduction.slice(0,6)){const prod=products.find(x=>x.id===p.productId);left.append(el('div',{class:'metric'},el('div',{},el('strong',{},`${prod?.name||'Produto'} × ${p.qty||1}`),el('div',{class:'muted small'},p.status||'Preparar')),badge(p.status||'Preparar',statusKind(p.status))))}}else left.append(el('div',{class:'empty'},'Sem produções em curso.'));
  const right=el('div',{class:'card'},el('h2',{},'Atenção'));
  if(critical.length)for(const m of critical.slice(0,6))right.append(el('div',{class:'metric'},el('span',{},m.name),badge(`${m.stock||0} ${m.unit||''}`,'warn')));else right.append(el('div',{class:'empty'},'Sem alertas de stock.'));
  root.append(el('div',{class:'split'},left,right));
  return root;
}
function quick(icon,title,desc,on){return el('button',{class:'quick',type:'button',onclick:on},el('div',{style:'font-size:24px'},icon),el('strong',{},title),el('div',{class:'muted small'},desc))}
function kpi(label,value){return el('div',{class:'card'},el('div',{class:'muted small'},label),el('div',{class:'kpi'},String(value)))}

export async function atelierView(ctx,opts={}){
  const [batches,products,materials]=await Promise.all(['productionBatches','products','materials'].map(db.all));
  const root=el('div');root.append(el('div',{class:'toolbar'},button('+ Iniciar produção',()=>productionModal(ctx,products),'primary')));
  const active=batches.sort((a,b)=>String(b.createdAt).localeCompare(String(a.createdAt)));
  const cards=el('div',{class:'grid cols-2'});
  if(!active.length)cards.append(el('div',{class:'card empty'},'Ainda não existem produções.'));
  for(const b of active){const p=products.find(x=>x.id===b.productId);const fam=families[p?.family]||families.other;const stages=fam.stages;const idx=Math.max(0,stages.indexOf(b.status));const c=el('div',{class:'card'});c.append(el('div',{class:'section-title'},el('div',{},el('h3',{},`${fam.icon} ${p?.name||'Produto'}`),el('div',{class:'muted'},`${b.qty||1} un. · ${fmtDate(b.createdAt)}`)),badge(b.status||stages[0],b.status==='Pronto'?'ok':'violet')));const st=el('div',{class:'production-stage'});stages.forEach((s,i)=>st.append(el('span',{class:i<=idx?'done':''},s)));c.append(st);const ec=p?calcProduct(p,materials):null;if(ec)c.append(el('div',{class:'muted small'},`Custo estimado do lote: ${euro(ec.trueCost*Number(b.qty||1))}`));const acts=el('div',{class:'toolbar'});if(idx<stages.length-1)acts.append(button('Avançar etapa',async()=>{b.status=stages[idx+1];b.updatedAt=new Date().toISOString();await db.put('productionBatches',b);if(b.status==='Pronto'&&!b.stockPosted){await consumeStock(p,b.qty||1);b.stockPosted=true;await db.put('productionBatches',b)}ctx.refresh()},'primary'));acts.append(button('Eliminar',async()=>{if(confirm('Eliminar esta produção?')){await db.del('productionBatches',b.id);ctx.refresh()}},'danger'));c.append(acts);cards.append(c)}root.append(cards);if(opts.create)setTimeout(()=>productionModal(ctx,products),0);return root;
}
async function consumeStock(product,qty){if(!product)return;const mats=await db.all('materials');for(const r of product.recipe||[]){const m=mats.find(x=>x.id===r.materialId);if(!m)continue;const needed=Number(r.qty||0)*Number(qty||1)/Math.max(1,Number(product.batchUnits||1));m.stock=Number(m.stock||0)-needed;await db.put('materials',m);await db.put('stockMovements',{id:uid('mov'),materialId:m.id,type:'Consumo produção',qty:-needed,createdAt:new Date().toISOString(),ref:product.name});}}
function productionModal(ctx,products){const form=el('div',{class:'form-grid'});const ps=select('productId',[['','Selecionar produto'],...products.map(p=>[p.id,p.name])]);const qty=input('qty','1','number',{min:'1'});form.append(field('Produto',ps),field('Quantidade',qty));modal('Iniciar produção',form,{onSave:async()=>{if(!ps.value)return alert('Seleciona um produto.'),false;const p=products.find(x=>x.id===ps.value);await db.put('productionBatches',{id:uid('prod'),productId:p.id,qty:Number(qty.value||1),status:(families[p.family]||families.other).stages[0],createdAt:new Date().toISOString(),stockPosted:false});ctx.refresh();return true;}})}

export async function catalogView(ctx,opts={}){
  const [products,materials]=await Promise.all([db.all('products'),db.all('materials')]);const root=el('div');root.append(el('div',{class:'toolbar'},button('+ Novo produto',()=>productModal(ctx,products,materials),'primary')));
  const rows=products.map(p=>{const c=calcProduct(p,materials);const fam=families[p.family]||families.other;return [`${fam.icon} ${esc(p.name)}`,esc(p.sku||''),esc(fam.label),euro(p.price),euro(c.trueCost),`${c.margin.toFixed(1)}%`,euro(c.recommended),p.published?badge('Publicado','ok'):badge('Privado','info'),`<button class="btn ghost" data-edit-product="${p.id}">Editar</button>`]});const t=table(['Produto','SKU','Família','PVP','Custo real','Margem','PVP recomendado','Loja',''],rows);t.addEventListener('click',e=>{const id=e.target.dataset.editProduct;if(id)productModal(ctx,products,materials,products.find(p=>p.id===id))});root.append(t);if(opts.create)setTimeout(()=>productModal(ctx,products,materials),0);return root;
}
function productModal(ctx,products,materials,existing={}){const form=el('div',{class:'form-grid'});const fam=select('family',familyOptions(),existing.family||'candle');const sku=input('sku',existing.sku||nextSku(products,fam.value));let auto=!existing.sku;fam.addEventListener('change',()=>{if(auto)sku.value=nextSku(products,fam.value)});sku.addEventListener('input',()=>auto=false);const name=input('name',existing.name||'');const price=input('price',existing.price||'','number',{step:'0.01',min:'0'});const batchUnits=input('batchUnits',existing.batchUnits||1,'number',{min:'1'});const laborMinutes=input('laborMinutes',existing.laborMinutes||0,'number',{min:'0'});const laborRate=input('laborRate',existing.laborRate??5.8,'number',{step:'0.01'});const packaging=input('packagingCost',existing.packagingCost||0,'number',{step:'0.01'});const extras=input('extrasPct',existing.extrasPct??5,'number',{step:'0.1'});const waste=input('wastePct',existing.wastePct??10,'number',{step:'0.1'});const target=input('targetMarginPct',existing.targetMarginPct??60,'number',{step:'0.1'});const alertMargin=input('alertMarginPct',existing.alertMarginPct??40,'number',{step:'0.1'});const moldCost=input('moldCost',existing.moldCost||0,'number',{step:'0.01'});const moldLife=input('moldLife',existing.moldLife||0,'number',{min:'0'});const equipMin=input('equipmentMinutes',existing.equipmentMinutes||0,'number',{min:'0'});const equipRate=input('equipmentRate',existing.equipmentRate||0,'number',{step:'0.01'});const fee=input('paymentFeePct',existing.paymentFeePct||0,'number',{step:'0.1'});const wholesale=input('wholesalePrice',existing.wholesalePrice||0,'number',{step:'0.01'});const published=select('published',[['false','Não'],['true','Sim']],String(!!existing.published));const onlineDesc=textarea('onlineDescription',existing.onlineDescription||'');form.append(field('Família',fam),field('SKU',sku),field('Nome do produto',name),field('PVP praticado (€)',price),field('Unidades por lote',batchUnits),field('Tempo de trabalho/lote (min)',laborMinutes),field('Mão de obra €/h',laborRate),field('Embalagem/unidade (€)',packaging),field('Consumíveis/Extras (%)',extras),field('Desperdício/Defeito (%)',waste),field('Margem alvo (%)',target),field('Alerta margem (%)',alertMargin),field('Custo do molde (€)',moldCost),field('Vida útil do molde (un.)',moldLife),field('Equipamento/lote (min)',equipMin),field('Equipamento €/h',equipRate),field('Taxa de pagamento (%)',fee),field('PVP grossista (€)',wholesale),field('Publicado na futura loja',published),field('Descrição online',onlineDesc,true));
  const recipe=el('div',{class:'field span2'},el('label',{},'Ficha técnica — matérias por lote'));const list=el('div',{class:'grid'});const lines=(existing.recipe||[]).map(x=>({...x}));const renderLines=()=>{list.innerHTML='';lines.forEach((r,i)=>{const row=el('div',{class:'grid cols-3'});const ms=select('materialId',[['','Matéria'],...materials.map(m=>[m.id,`${m.name} (${m.unit||'un'})`])],r.materialId);const q=input('qty',r.qty||0,'number',{step:'0.001',min:'0'});const delb=button('Remover',()=>{lines.splice(i,1);renderLines()},'danger');ms.onchange=()=>r.materialId=ms.value;q.oninput=()=>r.qty=Number(q.value||0);row.append(ms,q,delb);list.append(row)});};recipe.append(list,button('+ Adicionar matéria',()=>{lines.push({materialId:'',qty:0});renderLines()},'secondary'));renderLines();form.append(recipe);
  modal(existing.id?'Editar produto':'Novo produto',form,{onSave:async()=>{if(!name.value.trim())return alert('Indica o nome.'),false;if(products.some(p=>p.id!==existing.id&&String(p.sku||'').toLowerCase()===sku.value.trim().toLowerCase()))return alert('Esse SKU já existe.'),false;if(Number(moldCost.value)>0&&Number(moldLife.value)<=0)return alert('Indica a vida útil do molde.'),false;const p={...existing,id:existing.id||uid('p'),family:fam.value,sku:sku.value.trim(),name:name.value.trim(),price:Number(price.value||0),batchUnits:Number(batchUnits.value||1),laborMinutes:Number(laborMinutes.value||0),laborRate:Number(laborRate.value||0),packagingCost:Number(packaging.value||0),extrasPct:Number(extras.value||0),wastePct:Number(waste.value||0),targetMarginPct:Number(target.value||0),alertMarginPct:Number(alertMargin.value||0),moldCost:Number(moldCost.value||0),moldLife:Number(moldLife.value||0),equipmentMinutes:Number(equipMin.value||0),equipmentRate:Number(equipRate.value||0),paymentFeePct:Number(fee.value||0),wholesalePrice:Number(wholesale.value||0),published:published.value==='true',onlineDescription:onlineDesc.value,recipe:lines.filter(r=>r.materialId&&Number(r.qty)>0),updatedAt:new Date().toISOString(),createdAt:existing.createdAt||new Date().toISOString()};await db.put('products',p);ctx.refresh();return true;}})}

export async function materialsView(ctx,opts={}){const mats=await db.all('materials');const root=el('div');root.append(el('div',{class:'toolbar'},button('+ Nova matéria',()=>materialModal(ctx),'primary'),button('Registar compra',()=>purchaseModal(ctx,mats),'secondary')));const rows=mats.map(m=>[esc(m.name),esc(m.category||''),`${Number(m.stock||0).toFixed(2)} ${esc(m.unit||'')}`,euro(m.unitCost),`${Number(m.minStock||0).toFixed(2)}`,Number(m.stock)<=Number(m.minStock||0)?badge('Comprar','warn'):badge('OK','ok'),`<button class="btn ghost" data-edit-material="${m.id}">Editar</button>`]);const t=table(['Matéria','Categoria','Stock','Custo médio','Mínimo','Estado',''],rows);t.addEventListener('click',e=>{const id=e.target.dataset.editMaterial;if(id)materialModal(ctx,mats.find(m=>m.id===id))});root.append(t);if(opts.purchase)setTimeout(()=>purchaseModal(ctx,mats),0);return root;}
function materialModal(ctx,existing={}){const form=el('div',{class:'form-grid'});const name=input('name',existing.name||'');const cat=select('category',materialCategories.map(x=>[x,x]),existing.category||materialCategories[0]);const unit=select('unit',[['g','g'],['ml','ml'],['un','un'],['kg','kg'],['l','l']],existing.unit||'g');const stock=input('stock',existing.stock||0,'number',{step:'0.001'});const min=input('minStock',existing.minStock||0,'number',{step:'0.001'});const cost=input('unitCost',existing.unitCost||0,'number',{step:'0.0001'});form.append(field('Nome',name),field('Categoria',cat),field('Unidade base',unit),field('Stock atual',stock),field('Stock mínimo',min),field('Custo médio por unidade',cost));modal(existing.id?'Editar matéria':'Nova matéria',form,{onSave:async()=>{if(!name.value.trim())return false;await db.put('materials',{...existing,id:existing.id||uid('m'),name:name.value.trim(),category:cat.value,unit:unit.value,stock:Number(stock.value||0),minStock:Number(min.value||0),unitCost:Number(cost.value||0),updatedAt:new Date().toISOString()});ctx.refresh();return true;}})}
function purchaseModal(ctx,mats){const form=el('div',{class:'form-grid'});const ms=select('materialId',[['','Selecionar matéria'],...mats.map(m=>[m.id,m.name])]);const qty=input('qty','','number',{step:'0.001',min:'0'});const total=input('total','','number',{step:'0.01',min:'0'});form.append(field('Matéria',ms),field('Quantidade recebida (unidade base)',qty),field('Total pago (€)',total));modal('Registar compra',form,{onSave:async()=>{const m=mats.find(x=>x.id===ms.value);if(!m||Number(qty.value)<=0)return alert('Preenche a compra.'),false;const oldQty=Number(m.stock||0),oldCost=Number(m.unitCost||0),newQty=Number(qty.value),paid=Number(total.value||0);m.unitCost=(oldQty*oldCost+paid)/(oldQty+newQty);m.stock=oldQty+newQty;await db.put('materials',m);await db.put('purchases',{id:uid('buy'),materialId:m.id,qty:newQty,total:paid,createdAt:new Date().toISOString()});await db.put('stockMovements',{id:uid('mov'),materialId:m.id,type:'Compra',qty:newQty,createdAt:new Date().toISOString()});ctx.refresh();return true;}})}

export async function clientsView(ctx){const clients=await db.all('clients');const root=el('div');root.append(el('div',{class:'toolbar'},button('+ Novo cliente',()=>clientModal(ctx),'primary')));const rows=clients.map(c=>[esc(c.name),esc(c.phone||''),esc(c.email||''),esc(c.notes||''),`<button class="btn ghost" data-edit-client="${c.id}">Editar</button>`]);const t=table(['Cliente','Telefone','Email','Notas',''],rows);t.addEventListener('click',e=>{const id=e.target.dataset.editClient;if(id)clientModal(ctx,clients.find(c=>c.id===id))});root.append(t);return root;}
function clientModal(ctx,existing={}){const form=el('div',{class:'form-grid'});const name=input('name',existing.name||'');const phone=input('phone',existing.phone||'');const email=input('email',existing.email||'','email');const notes=textarea('notes',existing.notes||'');form.append(field('Nome',name),field('Telefone',phone),field('Email',email),field('Notas',notes,true));modal(existing.id?'Editar cliente':'Novo cliente',form,{onSave:async()=>{if(!name.value.trim())return false;await db.put('clients',{...existing,id:existing.id||uid('c'),name:name.value.trim(),phone:phone.value,email:email.value,notes:notes.value,updatedAt:new Date().toISOString()});ctx.refresh();return true;}})}

export async function ordersView(ctx,opts={}){const [orders,clients,items,products]=await Promise.all(['orders','clients','orderItems','products'].map(db.all));const root=el('div');root.append(el('div',{class:'toolbar'},button('+ Nova encomenda',()=>orderModal(ctx,clients,products),'primary')));const rows=orders.sort((a,b)=>String(b.createdAt).localeCompare(String(a.createdAt))).map(o=>{const c=clients.find(x=>x.id===o.clientId);const its=items.filter(i=>i.orderId===o.id);const total=its.reduce((s,i)=>s+Number(i.qty||0)*Number(i.unitPrice||0),0);return [esc(o.number||''),esc(c?.name||'Sem cliente'),fmtDate(o.dueDate),badge(o.status,statusKind(o.status)),its.reduce((s,i)=>s+Number(i.qty||0),0),euro(total),`<button class="btn ghost" data-edit-order="${o.id}">Editar</button>`]});const t=table(['N.º','Cliente','Data','Estado','Un.','Total',''],rows);t.addEventListener('click',e=>{const id=e.target.dataset.editOrder;if(id)orderModal(ctx,clients,products,orders.find(o=>o.id===id),items.filter(i=>i.orderId===id))});root.append(t);if(opts.create)setTimeout(()=>orderModal(ctx,clients,products),0);return root;}
function orderModal(ctx,clients,products,existing={},existingItems=[]){const form=el('div',{class:'form-grid'});const client=select('clientId',[['','Sem cliente'],...clients.map(c=>[c.id,c.name])],existing.clientId||'');const status=select('status',orderStatuses.map(s=>[s,s]),existing.status||'Orçamento');const due=input('dueDate',existing.dueDate||'','date');const notes=textarea('notes',existing.notes||'');form.append(field('Cliente',client),field('Estado',status),field('Data pretendida',due),field('Notas / personalização',notes,true));const lines=existingItems.map(x=>({...x}));const itemsBox=el('div',{class:'field span2'},el('label',{},'Artigos'));const list=el('div',{class:'grid'});const render=()=>{list.innerHTML='';lines.forEach((it,i)=>{const row=el('div',{class:'grid cols-3'});const ps=select('productId',[['','Produto'],...products.map(p=>[p.id,p.name])],it.productId);const q=input('qty',it.qty||1,'number',{min:'1'});const delb=button('Remover',()=>{lines.splice(i,1);render()},'danger');ps.onchange=()=>{it.productId=ps.value;const p=products.find(x=>x.id===ps.value);it.unitPrice=Number(p?.price||0);it.productName=p?.name||''};q.oninput=()=>it.qty=Number(q.value||1);row.append(ps,q,delb);list.append(row)});};itemsBox.append(list,button('+ Adicionar artigo',()=>{lines.push({id:uid('oi'),productId:'',qty:1,unitPrice:0});render()},'secondary'));render();form.append(itemsBox);modal(existing.id?'Editar encomenda':'Nova encomenda',form,{onSave:async()=>{if(!lines.some(x=>x.productId))return alert('Adiciona pelo menos um artigo.'),false;const id=existing.id||uid('o');const number=existing.number||`AE-${new Date().getFullYear()}-${String(Date.now()).slice(-5)}`;await db.put('orders',{...existing,id,number,clientId:client.value,status:status.value,dueDate:due.value,notes:notes.value,createdAt:existing.createdAt||new Date().toISOString(),updatedAt:new Date().toISOString()});for(const old of existingItems)await db.del('orderItems',old.id);for(const it of lines.filter(x=>x.productId)){const p=products.find(x=>x.id===it.productId);await db.put('orderItems',{...it,id:it.id||uid('oi'),orderId:id,productId:p.id,productName:p.name,qty:Number(it.qty||1),unitPrice:Number(it.unitPrice||p.price||0)});}ctx.refresh();return true;}})}

export async function financeView(){const [orders,items,expenses,investments,cash]=await Promise.all(['orders','orderItems','expenses','investments','cashMovements'].map(db.all));const valid=new Set(orders.filter(o=>o.status!=='Cancelada').map(o=>o.id));const revenue=items.filter(i=>valid.has(i.orderId)).reduce((s,i)=>s+Number(i.qty||0)*Number(i.unitPrice||0),0);const expense=expenses.reduce((s,x)=>s+Number(x.amount||0),0);const inv=investments.reduce((s,x)=>s+Number(x.amount||0),0);const root=el('div',{class:'grid'});root.append(el('div',{class:'grid cols-4'},kpi('Vendas registadas',euro(revenue)),kpi('Despesas',euro(expense)),kpi('Investimentos',euro(inv)),kpi('Resultado simples',euro(revenue-expense))));root.append(el('div',{class:'card'},el('h3',{},'Finanças'),el('p',{class:'muted'},'A área financeira está separada do motor de custos dos produtos. Compras de stock atualizam custo médio e stock; despesas operacionais e investimentos continuam registados separadamente.')));return root;}

export async function shopView(){const products=await db.all('products');const published=products.filter(p=>p.published);const root=el('div',{class:'grid cols-2'});root.append(el('div',{class:'card'},el('h3',{},'Futura loja ArtEssencia'),el('div',{class:'kpi'},published.length),el('div',{class:'muted'},'produtos marcados para publicação'),el('p',{},'Esta área fica preparada para ligar a mesma base Supabase à futura loja online, sem expor custos internos, fornecedores ou margens.')));root.append(el('div',{class:'card'},el('h3',{},'Estrutura prevista'),el('div',{class:'metric-list'},...['Produtos publicados','Coleções sazonais','Kits & presentes','Personalizações','Homepage','Campanhas','Entregas','Encomendas online → Backoffice'].map(x=>el('div',{class:'metric'},el('span',{},x),badge('Preparado','info'))))));return root;}

export async function reportsView(){const [products,materials,orders,items]=await Promise.all(['products','materials','orders','orderItems'].map(db.all));const root=el('div',{class:'grid cols-3'});root.append(kpi('Produtos',products.length),kpi('Matérias',materials.length),kpi('Encomendas',orders.length));const valid=new Set(orders.filter(o=>o.status!=='Cancelada').map(o=>o.id));const byProd={};for(const i of items.filter(i=>valid.has(i.orderId))){const k=i.productName||i.productId;byProd[k]??={qty:0,revenue:0};byProd[k].qty+=Number(i.qty||0);byProd[k].revenue+=Number(i.qty||0)*Number(i.unitPrice||0)}const rows=Object.entries(byProd).sort((a,b)=>b[1].revenue-a[1].revenue).map(([k,v])=>[esc(k),v.qty,euro(v.revenue)]);const box=el('div',{class:'card',style:'grid-column:1/-1'},el('h3',{},'Vendas por produto'));box.append(table(['Produto','Unidades','Receita'],rows));root.append(box);return root;}

export async function auditView(){const root=el('div',{class:'grid'});const header=el('div',{class:'card'},el('div',{class:'section-title'},el('div',{},el('h2',{},'Auditoria 360º'),el('p',{class:'muted'},'Verificação única da integridade estrutural do atelier.')),button('Executar auditoria',async()=>renderAudit(await runAudit()),'primary')));const results=el('div',{id:'auditResults',class:'card'},el('div',{class:'empty'},'Executa a auditoria para analisar a aplicação.'));root.append(header,results);const renderAudit=r=>{results.innerHTML='';results.append(el('div',{class:'grid cols-3'},kpi('Erros',r.counts.error),kpi('Atenções',r.counts.warn),kpi('OK',r.counts.ok)));for(const x of r.issues)results.append(el('div',{class:'audit-row'},badge(x.level==='error'?'Erro':x.level==='warn'?'Atenção':'OK',x.level==='error'?'danger':x.level==='warn'?'warn':'ok'),el('div',{},el('strong',{},x.area),el('div',{class:'muted small'},x.message)),el('span',{},'')))};return root;}

export async function settingsView(ctx){const root=el('div',{class:'grid cols-2'});const cfg=el('div',{class:'card'},el('h3',{},'Aplicação'),el('div',{class:'metric'},el('span',{},'Versão'),el('strong',{},ctx.version?.app||'1.0.0')),el('div',{class:'metric'},el('span',{},'Schema alvo'),el('strong',{},ctx.version?.schema||'1.0.0')),el('p',{class:'muted'},'Este projeto deve permanecer no mesmo repositório GitHub e no mesmo projeto Vercel. As próximas versões substituem os ficheiros e preservam a base de dados.'));const backup=el('div',{class:'card'},el('h3',{},'Backup local'),el('p',{class:'muted'},'Exporta todos os dados locais antes de alterações importantes.'),button('Exportar backup',async()=>download(`ArtEssencia_Backup_${new Date().toISOString().slice(0,10)}.json`,JSON.stringify(await db.exportAll(),null,2)),'secondary'),el('br'),el('br'),button('Importar backup',()=>importBackup(ctx),'ghost'));const cloud=el('div',{class:'card'},el('h3',{},'Base ArtEssencia'),el('p',{},'A sincronização Supabase será ligada a um projeto exclusivo ArtEssencia, separado da DONART.'),el('div',{class:'notice'},'Arquitetura alvo: Backoffice ArtEssencia ↔ Supabase ArtEssencia ↔ futura Loja ArtEssencia.'));root.append(cfg,backup,cloud);return root;}
function importBackup(ctx){const i=document.createElement('input');i.type='file';i.accept='.json,application/json';i.onchange=async()=>{try{const f=i.files?.[0];if(!f)return;await db.importAll(JSON.parse(await f.text()));alert('Backup importado.');ctx.refresh()}catch(e){alert(`Erro: ${e.message}`)}};i.click()}

export const views={today:todayView,atelier:atelierView,orders:ordersView,catalog:catalogView,materials:materialsView,clients:clientsView,finance:financeView,shop:shopView,reports:reportsView,audit:auditView,settings:settingsView};
